version: '3'

############################################################################
# Docker compose for local development
#
# Time Zones:
#    America/Los_Angeles  # PST
#    America/Denver       # MST
#    America/Chicago      # CST
#    America/New_York     # EST


####### OAuth2 Authorization Server ########
services:
  auth-server:
    build: ./authorization-server
    environment:
      - TZ=America/Chicago
      - MYSQL_SERVER=db
      - MYSQL_DB=auth
      - MYSQL_USER=root
      - MYSQL_PASSWORD=AhEP2678
      - REDIS_HOST=redis
    ports:
      - 8080:80
    volumes:
      - ./authorization-server/:/var/www
      - ./authorization-server/public:/var/www/html


####### Redis #######
  redis:
    image: redis
  redisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - TZ=America/Chicago
      - REDIS_1_HOST=redis
    ports:
      - 8081:80


####### Maria DB ########
  db:
    image: mariadb
    environment:
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=AhEP2678
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=America/Chicago
      - PMA_USER=root
      - PMA_PASSWORD=AhEP2678
    ports:
      - 8082:80


####### Open LDAP #######
  ldap:
    image: osixia/openldap
  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - 8083:443
