version: '3'

services:
  oauth2:
    build: .
    environment:
#        TZ: America/Los_Angeles  # PST
#        TZ: America/Denver       # MST
        TZ: America/Chicago      # CST
#        TZ: America/New_York     # EST
    ports:
      - 8080:80
    volumes:
      - ./bin:/root/bin
      - ./oauth2/:/var/www
      - ./oauth2/public:/var/www/html

