version: '3'

############################################################################
# Docker compose for local development
#
# Time Zones:
#    America/Los_Angeles  # PST
#    America/Denver       # MST
#    America/Chicago      # CST
#    America/New_York     # EST


####### OAuth2 Authorization Server ########
services:
  auth-server:
    build: ./authorization-server
    environment:
      - TZ=America/Chicago
      - DB=mysql://auth:naked@db:3306/auth
      - HISTORY_DB=mysql://auth:naked@db:3306/auth_history
#      - REDIS=redis://redis
#      - LDAP=msldap://adserver  # or openldap://ldapserver
#      - OAUTH2=phpoauth2://client_id:secreat@oauth2.loopback.world/return_url
      - XDEBUG_CONFIG="remote_host=host.docker.internal remote_port=9000 remote_autostart=1"
      - PHP_IDE_CONFIG=serverName=docker-cli
      - PMA_USER=root          # Do Not set this in production, for self db creation only !!!!
      - PMA_PASSWORD=AhEP2678  # Do Not set this in production, for self db creation only !!!!
    ports:
      - 9080:80
    volumes:
      - ./bin:/root/bin                             # Allow the master git project to interact with Docker container
      - ./authorization-server/:/var/www            # Override the web root
      - ./authorization-server/public:/var/www/html # Override the document root


####### Redis #######
  redis:
    image: redis
  redisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - TZ=America/Chicago
      - REDIS_1_HOST=redis
    ports:
      - 9081:80


####### Maria DB ########
  db:
    image: mariadb
    environment:
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=AhEP2678
    ports:
      - 5000:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=America/Chicago
      - PMA_USER=root
      - PMA_PASSWORD=AhEP2678
    ports:
      - 9082:80


####### Open LDAP #######
  ldap:
    image: osixia/openldap
  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - 9083:443
