version: '3'

############################################################################
# Docker compose for local development
#
# Time Zones:
#    America/Los_Angeles  # PST
#    America/Denver       # MST
#    America/Chicago      # CST
#    America/New_York     # EST


services:
  oauth2:
    build: .
    environment:
      - TZ=America/Chicago
      - MYSQL_USER=root
      - MYSQL_PASSWORD=AhEP2678
      - REDIS_HOST=redis
    ports:
      - 8080:80
    volumes:
      - ./bin:/root/bin
      - ./oauth2/:/var/www
      - ./oauth2/public:/var/www/html
  redis:
    image: redis
  redisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - TZ=America/Chicago
      - REDIS_1_HOST=redis
    ports:
      - 8081:80
  db:
    image: mariadb
    environment:
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=AhEP2678
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=America/Chicago
      - PMA_USER=root
      - PMA_PASSWORD=AhEP2678
    ports:
      - 8082:80
  ldap-service:
    image: osixia/openldap
  phpldapadmin-service:
    image: osixia/phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-service
    ports:
      - 8083:443


